const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Builds the GitHub Pages site by inlining report JSON directly into the
// HTML template. The result is a single self-contained index.html that
// works without a server and without separate data files.
//
// Also copies the raw JSON into docs/data/ as a fallback / for direct access.
//
// Usage:
//   node build-site.js
//   node build-site.js --reports-dir ./reports --docs-dir ./docs
//   node build-site.js --lists-file ./output/army-lists-latest.json
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

function getArg(flag) {
  const idx = args.indexOf(flag);
  return idx !== -1 && idx + 1 < args.length ? args[idx + 1] : null;
}

const reportsDir = getArg('--reports-dir') || path.join(__dirname, 'reports');
const docsDir    = getArg('--docs-dir')    || path.join(__dirname, 'docs');
const listsFile  = getArg('--lists-file')  || path.join(__dirname, 'output', 'army-lists-latest.json');
const dataDir    = path.join(docsDir, 'data');
const templatePath = path.join(docsDir, 'template.html');
const outputPath   = path.join(docsDir, 'index.html');

// ---------------------------------------------------------------------------

/**
 * Prevent sequences inside JSON from breaking the surrounding <script> block.
 * - </script> would close the tag prematurely.
 * - <!-- can trigger legacy HTML-comment handling inside scripts in some browsers.
 */
function escapeForScriptTag(jsonStr) {
  return jsonStr
    .replace(/<\/script>/gi, '<\\/script>')
    .replace(/<!--/g, '<\\!--');
}

/**
 * Generates llms.txt (site overview + data links) and llms-full.txt
 * (concatenated plain-text reports) in docsDir so LLMs can read the site
 * without parsing the JavaScript-heavy index.html.
 *
 * @param {string} reportsDir - Path to the reports directory
 * @param {string} docsDir    - Path to the docs output directory
 * @param {object|null} metaData - Parsed meta-report JSON (for faction/timestamp)
 */
function buildLlmsFiles(reportsDir, docsDir, metaData) {
  const faction     = metaData?.faction    || 'Unknown Faction';
  const generatedAt = metaData?.generatedAt || new Date().toISOString();

  // --- llms.txt ---
  const llmsTxt = [
    `# Listhammer — ${faction} Meta Analyser`,
    '',
    '> Automated Warhammer 40K tournament army list analysis, powered by Claude AI.',
    `> Last updated: ${generatedAt}`,
    '',
    '## What is this?',
    '',
    'This site crawls top-finishing tournament army lists from listhammer.info, runs',
    'statistical meta analysis, and produces AI-generated per-list and per-detachment',
    'characterizations for competitive play.',
    '',
    '## Site Structure',
    '',
    '3-tab interface:',
    '- **Lists** — all lists sortable by date/event size; expandable cards with full',
    '  army list text, AI archetype + game plan, novelty badges for new lists.',
    '- **By Detachment** — lists grouped by detachment; AI summary; unit frequency',
    '  table; variance (contested choices); novelty flags; collapsible list cards.',
    '- **Patterns** — AI cross-detachment overview and crawl diff summary.',
    '',
    '## Data Endpoints',
    '',
    'These files contain the raw structured data:',
    '',
    '- [Meta Report](data/meta-report.json)',
    '  Detachment breakdown, crawl diff (new/dropped lists, new tech), lists by detachment.',
    '',
    '- [Army Optimizer](data/optimizer.json)',
    '  Per-detachment unit/enhancement frequency, variance (contested choices),',
    '  novelty flags (tech not seen in previous crawl), unit co-occurrence pairs.',
    '',
    '- [AI Analysis](data/ai-analysis.json)',
    '  Claude-generated per-list characterizations (archetype, game plan, tech diffs),',
    '  per-detachment summaries, cross-detachment patterns, crawl diff prose.',
    '',
    '- [Army Lists](data/army-lists.json)',
    '  Raw crawled list data with firstSeen/lastSeen timestamps.',
    '',
    '## Full Plain-Text Report',
    '',
    'For a single human/LLM-readable document with all analysis:',
    '[llms-full.txt](llms-full.txt)',
    '',
    '## Important Dataset Context',
    '',
    'ALL lists in this dataset are top-finishing results (1st or 2nd place at their',
    'tournament). This dataset does NOT represent the general player field.',
    'Do not infer win rates or comparative skill from list frequency.',
    '',
    '## How to Interpret',
    '',
    '- List frequency = how many top-finishing players chose a given unit or detachment.',
    '- "Undefeated" = 0 recorded losses at an event (draws allowed).',
    `- Lists are from ${faction} players at tracked 40K events.`,
    '- AI characterizations are generated by Claude with strict no-win-rate rules.',
    '  All claims are grounded in list count and unit inclusion rate only.',
    '- noveltyFlags = units/enhancements not seen in the previous crawl.',
    '- varianceAnalysis = units appearing in 20–79% of a detachment\'s lists (contested picks).',
  ].join('\n');

  fs.writeFileSync(path.join(docsDir, 'llms.txt'), llmsTxt, 'utf-8');
  console.log('  Generated llms.txt');

  // --- llms-full.txt ---
  const reportFiles = [
    { file: 'meta-report-latest.txt', label: 'META REPORT' },
    { file: 'optimizer-latest.txt',   label: 'ARMY OPTIMIZER' },
    { file: 'ai-analysis-latest.txt', label: 'AI ANALYSIS' },
  ];

  const separator = '='.repeat(80);
  const sections = [
    `Listhammer Meta Analysis — ${faction}  |  Generated: ${generatedAt}`,
    separator,
  ];

  for (const { file, label } of reportFiles) {
    const srcPath = path.join(reportsDir, file);
    if (fs.existsSync(srcPath)) {
      sections.push('', fs.readFileSync(srcPath, 'utf-8').trim());
    } else {
      sections.push('', `[${label}: not available — run the full pipeline to generate this section]`);
    }
  }

  fs.writeFileSync(path.join(docsDir, 'llms-full.txt'), sections.join('\n'), 'utf-8');
  console.log('  Generated llms-full.txt');
}

function main() {
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }

  // Read template
  if (!fs.existsSync(templatePath)) {
    console.error(`Template not found: ${templatePath}`);
    process.exit(1);
  }
  let html = fs.readFileSync(templatePath, 'utf-8');

  let embedded = 0;

  // Meta report
  const metaSrc = path.join(reportsDir, 'meta-report-latest.json');
  let metaJSON = 'null';
  if (fs.existsSync(metaSrc)) {
    metaJSON = fs.readFileSync(metaSrc, 'utf-8');
    fs.copyFileSync(metaSrc, path.join(dataDir, 'meta-report.json'));
    console.log('  Embedded meta report');
    embedded++;
  } else {
    console.warn('  Warning: meta report not found — run "npm run report" first');
  }

  // Optimizer report
  const optSrc = path.join(reportsDir, 'optimizer-latest.json');
  let optJSON = 'null';
  if (fs.existsSync(optSrc)) {
    optJSON = fs.readFileSync(optSrc, 'utf-8');
    fs.copyFileSync(optSrc, path.join(dataDir, 'optimizer.json'));
    console.log('  Embedded optimizer report');
    embedded++;
  } else {
    console.warn('  Warning: optimizer report not found — run "npm run optimize" first');
  }

  // AI analysis report
  const aiSrc = path.join(reportsDir, 'ai-analysis-latest.json');
  let aiJSON = 'null';
  if (fs.existsSync(aiSrc)) {
    const aiData = JSON.parse(fs.readFileSync(aiSrc, 'utf-8'));
    // Only embed if the analysis was not skipped / is not an empty placeholder
    if (!aiData.skipped) {
      aiJSON = JSON.stringify(aiData);
      fs.copyFileSync(aiSrc, path.join(dataDir, 'ai-analysis.json'));
      console.log('  Embedded AI analysis');
      embedded++;
    } else {
      console.warn(`  AI analysis skipped (${aiData.reason || 'no reason given'}) — embedding placeholder`);
      aiJSON = JSON.stringify({ skipped: true, reason: aiData.reason || 'AI analysis was skipped' });
    }
  } else {
    console.warn('  Warning: AI analysis not found — embedding placeholder (run "npm run ai-analysis" to generate)');
    aiJSON = JSON.stringify({ skipped: true, reason: 'AI analysis was not run. Set ANTHROPIC_API_KEY and run "npm run ai-analysis".' });
  }

  // Army lists (for INLINE_LISTS — expandable card decklists)
  let listsJSON = 'null';
  if (fs.existsSync(listsFile)) {
    listsJSON = fs.readFileSync(listsFile, 'utf-8');
    fs.copyFileSync(listsFile, path.join(dataDir, 'army-lists.json'));
    console.log('  Embedded army lists');
    embedded++;
  } else {
    console.warn(`  Warning: army lists not found at ${listsFile} — run "npm run crawl:dg" first`);
  }

  // Inject data into the template
  // The template uses the pattern: var X = /*__PLACEHOLDER__*/null;
  // We need to replace both the comment AND the trailing null to avoid syntax errors
  html = html.replace('/*__META_REPORT_DATA__*/null',  escapeForScriptTag(metaJSON));
  html = html.replace('/*__OPTIMIZER_DATA__*/null',    escapeForScriptTag(optJSON));
  html = html.replace('/*__AI_ANALYSIS_DATA__*/null',  escapeForScriptTag(aiJSON));
  html = html.replace('/*__LISTS_DATA__*/null',        escapeForScriptTag(listsJSON));

  fs.writeFileSync(outputPath, html, 'utf-8');

  if (embedded === 0) {
    console.warn('\nNo reports found — site will show empty state.');
  }

  console.log(`\nSite built -> ${path.relative(__dirname, outputPath)} (${embedded} report${embedded > 1 ? 's' : ''} inlined)`);
  console.log('Deploy docs/ to GitHub Pages, or open index.html in a browser.');

  // Generate LLM-readable files
  buildLlmsFiles(reportsDir, docsDir, metaJSON !== 'null' ? JSON.parse(metaJSON).meta || JSON.parse(metaJSON) : null);
}

main();
